# Generated by Django 5.0.6 on 2024-05-09 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comandas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barraca',
            name='responsavel',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
